x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - ./box:/box
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "2358:2358"
    # privileged: true
    <<: *default-logging
    restart: always

  worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - ./box:/box 
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:17
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"   
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: ["redis-server", "--appendonly", "no"]
    restart: always
    <<: *default-logging

volumes:
  data:
